-- MySQL Script generated by MySQL Workbench
-- Fri Mar 13 22:18:58 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema genie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema genie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `genie` DEFAULT CHARACTER SET utf8 ;
USE `genie` ;

-- -----------------------------------------------------
-- Table `genie`.`Wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genie`.`Wishlist` (
  `id` INT NOT NULL,
  `wishlist_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genie`.`WishlistItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geniep.`.`WishlistItem` (
  `id` INT NOT NULL,
  `sku` VARCHAR(45) NULL, 
  `title` VARCHAR(45) NULL,
  `image_url` VARCHAR(45) NULL,
  `catalog_price` VARCHAR(45) NULL,
  `brand` VARCHAR(45) NULL,
  `review_score` VARCHAR(45) NULL,
  `wishlist` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `wishlist_idx` (`wishlist` ASC) VISIBLE,
  CONSTRAINT `wishlist`
    FOREIGN KEY (`wishlist`)
    REFERENCES `genie`.`Wishlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genie`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genie`.`Customer` (
  `id` INT NOT NULL,
  `customer_id` VARCHAR(45) NULL,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  `wishlist` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `wishlist_idx` (`wishlist` ASC) VISIBLE,
  CONSTRAINT `wishlist`
    FOREIGN KEY (`wishlist`)
    REFERENCES `genie`.`Wishlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
